### ISSUE TITLE
Allow option to prevent Databricks Job from being run after being submitted.

### ISSUE THREAD

**Issue by Jorricks** [schipholgroup/takeoff#55]
After inspecting [takeoff/azure/deploy_to_databricks.py](https://github.com/schipholgroup/takeoff/blob/master/takeoff/azure/deploy_to_databricks.py), there seems to be no option to do prevent the job from being run.

As I plan to schedule the job elsewhere, I don't need the job to be run after it has been submitted as a new DBJ.

**Comment by danielvdende** [comment]
@Jorricks could you take a look if this issue is resolved now by #60 ?

**Comment by Jorricks** [comment]
This definitely solved it! I will use this in the next project.
